amdgpu/dc: Fix missing null checks in amdgpu_dm.c
From smatch:
error: we previously assumed X could be null

Signed-off-by: Ernst Sjöstrand <ernstp@gmail.com>